import type { Metadata } from "next";
import "./globals.css";
import { LoadingProvider } from "../contexts/LoadingContext";
import { ToastProvider } from "../contexts/ToastContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased" suppressHydrationWarning={true}>
        <LoadingProvider>
          <ToastProvider>
            {children}
          </ToastProvider>
        </LoadingProvider>
      </body>
    </html>
  );
}
