import type { Metadata } from "next";
import { LoadingProvider } from "../contexts/LoadingContext";
import { ToastProvider } from "../contexts/ToastContext";
import ReactQueryProvider from "../providers/ReactQueryProvider";
import "react-photo-view/dist/react-photo-view.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased" suppressHydrationWarning={true}>
        <ReactQueryProvider>
          <LoadingProvider>
            <ToastProvider>
              {children}
            </ToastProvider>
          </LoadingProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
